tasks:
  - init: |
      sudo docker pull projectorimages/projector-idea-c:latest
      sudo docker pull projectorimages/projector-idea-u:latest
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains

      # Community Edition
      sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-intellij-idea/.jetbrains:/home/projector-user -it projectorimages/projector-idea-c

      # Ultimate Edition
      #sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-intellij-idea/.jetbrains:/home/projector-user -it projectorimages/projector-idea-u

ports:
  - port: 8887
    visibility: private
    onOpen: open-browser



